### ISSUE TITLE
As Open-assistant  Plug-in

### ISSUE THREAD

**Issue by vasnt** [haseeb-heaven/CodeRunner-Plugin#1]
How to add it as plugin on https://open-assistant.io/chat/ ?

**Comment by haseeb-heaven** [comment]
You can try these Url to test it.
Maifest:
https://code-runner-plugin.vercel.app/.well-known/ai-plugin.json

Plugin:
https://code-runner-plugin.vercel.app/

I have already tested on OpenAssistant it’s working

**Comment by vasnt** [comment]
Thanks Haseeb for links, it is working perfectly at [OpenAssistant ](https://open-assistant.io/chat)
