### ISSUE TITLE
Bar charts problem

### ISSUE THREAD

**Issue by foruok** [haseeb-heaven/CodeRunner-Plugin#6]
我通过ChatGPT使用Code Runner，生成柱状图时，第一个标签名总是带有"["，最后一个标签名总是带有"]"。
我的ChatGPT提示语为：
请创建一个柱状图，标签为['一月','二月','三月','四月']，数据集为[{label:'销售额',data:[102,218,306,389]}]

![bar charts example](https://code-runner-plugin.vercel.app/download/graph_bar_12031.png)

**Comment by foruok** [comment]
console information was below:

{
  "chart_type": "bar",
  "labels": "['一月', '二月', '三月', '四月']",
  "datasets": [
    {
      "label": "销售额",
      "data": [
        102,
        218,
        306,
        389
      ]
    }
  ]
}

**Comment by haseeb-heaven** [comment]
**Chinese**:
您不必为数据集提供"["或"]",只需以简单语言提供数据集,而不是以JSON或任何数据交换格式提供。

**English**:
You dont have to provide the "[" or "]" with the dataset just provide dataset in plain language and not in JSON or in any data exchange format.

**Comment by haseeb-heaven** [comment]
And this seems issue with Chatgpt sending data to plugin and nothing wrong with the plugin itself

**Comment by foruok** [comment]
I test it use plain language.

Chinese:
请创建一个饼图，标签为：一月，二月，三月，四月。数据为：102，80，30，260。

the problem occurred again.

![](https://code-runner-plugin.vercel.app/download/graph_pie_99652.png)

I check what data  the ChatGPT sent，as below：

{
  "chart_type": "pie",
  "labels": "['一月','二月','三月','四月']",
  "datasets": [
    {
      "data": [
        102,
        80,
        30,
        260
      ]
    }
  ]
}

**Comment by haseeb-heaven** [comment]
<img width="829" alt="image" src="https://github.com/haseeb-heaven/CodeRunner-Plugin/assets/11544739/4f632285-1d16-4669-8d3f-6bfa00213406">

I also tested with same prompt you sent me i am not getting the "[" and "]" characters at the start and end of labels.

And this uses [quickchart](http://quickchart.io) to draw maybe they have problem with rendering labels in Chinese language

**Comment by foruok** [comment]
Okey，thanks a lot!
